// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/raa0121/go-kokoro-io/client/access_tokens"
	"github.com/raa0121/go-kokoro-io/client/bot"
	"github.com/raa0121/go-kokoro-io/client/channels"
	"github.com/raa0121/go-kokoro-io/client/devices"
	"github.com/raa0121/go-kokoro-io/client/memberships"
	"github.com/raa0121/go-kokoro-io/client/messages"
	"github.com/raa0121/go-kokoro-io/client/profiles"
)

// Default kokoro io API document HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "kokoro.io"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new kokoro io API document HTTP client.
func NewHTTPClient(formats strfmt.Registry) *KokoroIoAPIDocument {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new kokoro io API document HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *KokoroIoAPIDocument {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new kokoro io API document client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *KokoroIoAPIDocument {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(KokoroIoAPIDocument)
	cli.Transport = transport

	cli.AccessTokens = access_tokens.New(transport, formats)

	cli.Bot = bot.New(transport, formats)

	cli.Channels = channels.New(transport, formats)

	cli.Devices = devices.New(transport, formats)

	cli.Memberships = memberships.New(transport, formats)

	cli.Messages = messages.New(transport, formats)

	cli.Profiles = profiles.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// KokoroIoAPIDocument is a client for kokoro io API document
type KokoroIoAPIDocument struct {
	AccessTokens *access_tokens.Client

	Bot *bot.Client

	Channels *channels.Client

	Devices *devices.Client

	Memberships *memberships.Client

	Messages *messages.Client

	Profiles *profiles.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *KokoroIoAPIDocument) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.AccessTokens.SetTransport(transport)

	c.Bot.SetTransport(transport)

	c.Channels.SetTransport(transport)

	c.Devices.SetTransport(transport)

	c.Memberships.SetTransport(transport)

	c.Messages.SetTransport(transport)

	c.Profiles.SetTransport(transport)

}
