// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1ChannelsChannelIDMembershipsParams creates a new GetV1ChannelsChannelIDMembershipsParams object
// with the default values initialized.
func NewGetV1ChannelsChannelIDMembershipsParams() *GetV1ChannelsChannelIDMembershipsParams {
	var ()
	return &GetV1ChannelsChannelIDMembershipsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ChannelsChannelIDMembershipsParamsWithTimeout creates a new GetV1ChannelsChannelIDMembershipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1ChannelsChannelIDMembershipsParamsWithTimeout(timeout time.Duration) *GetV1ChannelsChannelIDMembershipsParams {
	var ()
	return &GetV1ChannelsChannelIDMembershipsParams{

		timeout: timeout,
	}
}

// NewGetV1ChannelsChannelIDMembershipsParamsWithContext creates a new GetV1ChannelsChannelIDMembershipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1ChannelsChannelIDMembershipsParamsWithContext(ctx context.Context) *GetV1ChannelsChannelIDMembershipsParams {
	var ()
	return &GetV1ChannelsChannelIDMembershipsParams{

		Context: ctx,
	}
}

// NewGetV1ChannelsChannelIDMembershipsParamsWithHTTPClient creates a new GetV1ChannelsChannelIDMembershipsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1ChannelsChannelIDMembershipsParamsWithHTTPClient(client *http.Client) *GetV1ChannelsChannelIDMembershipsParams {
	var ()
	return &GetV1ChannelsChannelIDMembershipsParams{
		HTTPClient: client,
	}
}

/*GetV1ChannelsChannelIDMembershipsParams contains all the parameters to send to the API endpoint
for the get v1 channels channel Id memberships operation typically these are written to a http.Request
*/
type GetV1ChannelsChannelIDMembershipsParams struct {

	/*ChannelID*/
	ChannelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) WithTimeout(timeout time.Duration) *GetV1ChannelsChannelIDMembershipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) WithContext(ctx context.Context) *GetV1ChannelsChannelIDMembershipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) WithHTTPClient(client *http.Client) *GetV1ChannelsChannelIDMembershipsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) WithChannelID(channelID string) *GetV1ChannelsChannelIDMembershipsParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the get v1 channels channel Id memberships params
func (o *GetV1ChannelsChannelIDMembershipsParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ChannelsChannelIDMembershipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", o.ChannelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
