// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// GetV1ChannelsChannelIDMessagesReader is a Reader for the GetV1ChannelsChannelIDMessages structure.
type GetV1ChannelsChannelIDMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ChannelsChannelIDMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1ChannelsChannelIDMessagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1ChannelsChannelIDMessagesOK creates a GetV1ChannelsChannelIDMessagesOK with default headers values
func NewGetV1ChannelsChannelIDMessagesOK() *GetV1ChannelsChannelIDMessagesOK {
	return &GetV1ChannelsChannelIDMessagesOK{}
}

/*GetV1ChannelsChannelIDMessagesOK handles this case with default header values.

Returns recent messages in the channel.
*/
type GetV1ChannelsChannelIDMessagesOK struct {
	Payload *models.MessageEntity
}

func (o *GetV1ChannelsChannelIDMessagesOK) Error() string {
	return fmt.Sprintf("[GET /v1/channels/{channel_id}/messages][%d] getV1ChannelsChannelIdMessagesOK  %+v", 200, o.Payload)
}

func (o *GetV1ChannelsChannelIDMessagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
