// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1ChannelsChannelIDParams creates a new GetV1ChannelsChannelIDParams object
// with the default values initialized.
func NewGetV1ChannelsChannelIDParams() *GetV1ChannelsChannelIDParams {
	var ()
	return &GetV1ChannelsChannelIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ChannelsChannelIDParamsWithTimeout creates a new GetV1ChannelsChannelIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1ChannelsChannelIDParamsWithTimeout(timeout time.Duration) *GetV1ChannelsChannelIDParams {
	var ()
	return &GetV1ChannelsChannelIDParams{

		timeout: timeout,
	}
}

// NewGetV1ChannelsChannelIDParamsWithContext creates a new GetV1ChannelsChannelIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1ChannelsChannelIDParamsWithContext(ctx context.Context) *GetV1ChannelsChannelIDParams {
	var ()
	return &GetV1ChannelsChannelIDParams{

		Context: ctx,
	}
}

// NewGetV1ChannelsChannelIDParamsWithHTTPClient creates a new GetV1ChannelsChannelIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1ChannelsChannelIDParamsWithHTTPClient(client *http.Client) *GetV1ChannelsChannelIDParams {
	var ()
	return &GetV1ChannelsChannelIDParams{
		HTTPClient: client,
	}
}

/*GetV1ChannelsChannelIDParams contains all the parameters to send to the API endpoint
for the get v1 channels channel Id operation typically these are written to a http.Request
*/
type GetV1ChannelsChannelIDParams struct {

	/*ChannelID*/
	ChannelID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) WithTimeout(timeout time.Duration) *GetV1ChannelsChannelIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) WithContext(ctx context.Context) *GetV1ChannelsChannelIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) WithHTTPClient(client *http.Client) *GetV1ChannelsChannelIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) WithChannelID(channelID int32) *GetV1ChannelsChannelIDParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the get v1 channels channel Id params
func (o *GetV1ChannelsChannelIDParams) SetChannelID(channelID int32) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ChannelsChannelIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", swag.FormatInt32(o.ChannelID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
