// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// GetV1ChannelsChannelIDMembershipsReader is a Reader for the GetV1ChannelsChannelIDMemberships structure.
type GetV1ChannelsChannelIDMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ChannelsChannelIDMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1ChannelsChannelIDMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1ChannelsChannelIDMembershipsOK creates a GetV1ChannelsChannelIDMembershipsOK with default headers values
func NewGetV1ChannelsChannelIDMembershipsOK() *GetV1ChannelsChannelIDMembershipsOK {
	return &GetV1ChannelsChannelIDMembershipsOK{}
}

/*GetV1ChannelsChannelIDMembershipsOK handles this case with default header values.

Returns all of members in this channel
*/
type GetV1ChannelsChannelIDMembershipsOK struct {
	Payload *models.ChannelWithMembershipsEntity
}

func (o *GetV1ChannelsChannelIDMembershipsOK) Error() string {
	return fmt.Sprintf("[GET /v1/channels/{channel_id}/memberships][%d] getV1ChannelsChannelIdMembershipsOK  %+v", 200, o.Payload)
}

func (o *GetV1ChannelsChannelIDMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelWithMembershipsEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
