// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PostV1ChannelsChannelIDMessagesReader is a Reader for the PostV1ChannelsChannelIDMessages structure.
type PostV1ChannelsChannelIDMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1ChannelsChannelIDMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostV1ChannelsChannelIDMessagesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV1ChannelsChannelIDMessagesCreated creates a PostV1ChannelsChannelIDMessagesCreated with default headers values
func NewPostV1ChannelsChannelIDMessagesCreated() *PostV1ChannelsChannelIDMessagesCreated {
	return &PostV1ChannelsChannelIDMessagesCreated{}
}

/*PostV1ChannelsChannelIDMessagesCreated handles this case with default header values.

Creates a new message.
*/
type PostV1ChannelsChannelIDMessagesCreated struct {
	Payload *models.MessageEntity
}

func (o *PostV1ChannelsChannelIDMessagesCreated) Error() string {
	return fmt.Sprintf("[POST /v1/channels/{channel_id}/messages][%d] postV1ChannelsChannelIdMessagesCreated  %+v", 201, o.Payload)
}

func (o *PostV1ChannelsChannelIDMessagesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
