// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PostV1ChannelsDirectMessageReader is a Reader for the PostV1ChannelsDirectMessage structure.
type PostV1ChannelsDirectMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1ChannelsDirectMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostV1ChannelsDirectMessageCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV1ChannelsDirectMessageCreated creates a PostV1ChannelsDirectMessageCreated with default headers values
func NewPostV1ChannelsDirectMessageCreated() *PostV1ChannelsDirectMessageCreated {
	return &PostV1ChannelsDirectMessageCreated{}
}

/*PostV1ChannelsDirectMessageCreated handles this case with default header values.

Creates a new direct message.
*/
type PostV1ChannelsDirectMessageCreated struct {
	Payload *models.ChannelEntity
}

func (o *PostV1ChannelsDirectMessageCreated) Error() string {
	return fmt.Sprintf("[POST /v1/channels/direct_message][%d] postV1ChannelsDirectMessageCreated  %+v", 201, o.Payload)
}

func (o *PostV1ChannelsDirectMessageCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
