// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PutV1ChannelsChannelIDArchiveReader is a Reader for the PutV1ChannelsChannelIDArchive structure.
type PutV1ChannelsChannelIDArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1ChannelsChannelIDArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1ChannelsChannelIDArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1ChannelsChannelIDArchiveOK creates a PutV1ChannelsChannelIDArchiveOK with default headers values
func NewPutV1ChannelsChannelIDArchiveOK() *PutV1ChannelsChannelIDArchiveOK {
	return &PutV1ChannelsChannelIDArchiveOK{}
}

/*PutV1ChannelsChannelIDArchiveOK handles this case with default header values.

Archive a channel.
*/
type PutV1ChannelsChannelIDArchiveOK struct {
	Payload *models.ChannelEntity
}

func (o *PutV1ChannelsChannelIDArchiveOK) Error() string {
	return fmt.Sprintf("[PUT /v1/channels/{channel_id}/archive][%d] putV1ChannelsChannelIdArchiveOK  %+v", 200, o.Payload)
}

func (o *PutV1ChannelsChannelIDArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
