// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutV1ChannelsChannelIDManageMembersMemberIDReader is a Reader for the PutV1ChannelsChannelIDManageMembersMemberID structure.
type PutV1ChannelsChannelIDManageMembersMemberIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1ChannelsChannelIDManageMembersMemberIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1ChannelsChannelIDManageMembersMemberIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1ChannelsChannelIDManageMembersMemberIDOK creates a PutV1ChannelsChannelIDManageMembersMemberIDOK with default headers values
func NewPutV1ChannelsChannelIDManageMembersMemberIDOK() *PutV1ChannelsChannelIDManageMembersMemberIDOK {
	return &PutV1ChannelsChannelIDManageMembersMemberIDOK{}
}

/*PutV1ChannelsChannelIDManageMembersMemberIDOK handles this case with default header values.

Changes the authority of member
*/
type PutV1ChannelsChannelIDManageMembersMemberIDOK struct {
}

func (o *PutV1ChannelsChannelIDManageMembersMemberIDOK) Error() string {
	return fmt.Sprintf("[PUT /v1/channels/{channel_id}/manage_members/{member_id}][%d] putV1ChannelsChannelIdManageMembersMemberIdOK ", 200)
}

func (o *PutV1ChannelsChannelIDManageMembersMemberIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
