// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PutV1ChannelsChannelIDUnarchiveReader is a Reader for the PutV1ChannelsChannelIDUnarchive structure.
type PutV1ChannelsChannelIDUnarchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1ChannelsChannelIDUnarchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1ChannelsChannelIDUnarchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1ChannelsChannelIDUnarchiveOK creates a PutV1ChannelsChannelIDUnarchiveOK with default headers values
func NewPutV1ChannelsChannelIDUnarchiveOK() *PutV1ChannelsChannelIDUnarchiveOK {
	return &PutV1ChannelsChannelIDUnarchiveOK{}
}

/*PutV1ChannelsChannelIDUnarchiveOK handles this case with default header values.

Unarchive a channel.
*/
type PutV1ChannelsChannelIDUnarchiveOK struct {
	Payload *models.ChannelEntity
}

func (o *PutV1ChannelsChannelIDUnarchiveOK) Error() string {
	return fmt.Sprintf("[PUT /v1/channels/{channel_id}/unarchive][%d] putV1ChannelsChannelIdUnarchiveOK  %+v", 200, o.Payload)
}

func (o *PutV1ChannelsChannelIDUnarchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
