// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutV1ChannelsChannelIDUnarchiveParams creates a new PutV1ChannelsChannelIDUnarchiveParams object
// with the default values initialized.
func NewPutV1ChannelsChannelIDUnarchiveParams() *PutV1ChannelsChannelIDUnarchiveParams {
	var ()
	return &PutV1ChannelsChannelIDUnarchiveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutV1ChannelsChannelIDUnarchiveParamsWithTimeout creates a new PutV1ChannelsChannelIDUnarchiveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutV1ChannelsChannelIDUnarchiveParamsWithTimeout(timeout time.Duration) *PutV1ChannelsChannelIDUnarchiveParams {
	var ()
	return &PutV1ChannelsChannelIDUnarchiveParams{

		timeout: timeout,
	}
}

// NewPutV1ChannelsChannelIDUnarchiveParamsWithContext creates a new PutV1ChannelsChannelIDUnarchiveParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutV1ChannelsChannelIDUnarchiveParamsWithContext(ctx context.Context) *PutV1ChannelsChannelIDUnarchiveParams {
	var ()
	return &PutV1ChannelsChannelIDUnarchiveParams{

		Context: ctx,
	}
}

// NewPutV1ChannelsChannelIDUnarchiveParamsWithHTTPClient creates a new PutV1ChannelsChannelIDUnarchiveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutV1ChannelsChannelIDUnarchiveParamsWithHTTPClient(client *http.Client) *PutV1ChannelsChannelIDUnarchiveParams {
	var ()
	return &PutV1ChannelsChannelIDUnarchiveParams{
		HTTPClient: client,
	}
}

/*PutV1ChannelsChannelIDUnarchiveParams contains all the parameters to send to the API endpoint
for the put v1 channels channel Id unarchive operation typically these are written to a http.Request
*/
type PutV1ChannelsChannelIDUnarchiveParams struct {

	/*ChannelID*/
	ChannelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) WithTimeout(timeout time.Duration) *PutV1ChannelsChannelIDUnarchiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) WithContext(ctx context.Context) *PutV1ChannelsChannelIDUnarchiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) WithHTTPClient(client *http.Client) *PutV1ChannelsChannelIDUnarchiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) WithChannelID(channelID string) *PutV1ChannelsChannelIDUnarchiveParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the put v1 channels channel Id unarchive params
func (o *PutV1ChannelsChannelIDUnarchiveParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *PutV1ChannelsChannelIDUnarchiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", o.ChannelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
