// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// DeleteV1DevicesDeviceIdentifierReader is a Reader for the DeleteV1DevicesDeviceIdentifier structure.
type DeleteV1DevicesDeviceIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1DevicesDeviceIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteV1DevicesDeviceIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteV1DevicesDeviceIdentifierOK creates a DeleteV1DevicesDeviceIdentifierOK with default headers values
func NewDeleteV1DevicesDeviceIdentifierOK() *DeleteV1DevicesDeviceIdentifierOK {
	return &DeleteV1DevicesDeviceIdentifierOK{}
}

/*DeleteV1DevicesDeviceIdentifierOK handles this case with default header values.

Delete a device
*/
type DeleteV1DevicesDeviceIdentifierOK struct {
	Payload *models.DeviceEntity
}

func (o *DeleteV1DevicesDeviceIdentifierOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/devices/{device_identifier}][%d] deleteV1DevicesDeviceIdentifierOK  %+v", 200, o.Payload)
}

func (o *DeleteV1DevicesDeviceIdentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
