// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1DevicesParams creates a new GetV1DevicesParams object
// with the default values initialized.
func NewGetV1DevicesParams() *GetV1DevicesParams {

	return &GetV1DevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DevicesParamsWithTimeout creates a new GetV1DevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1DevicesParamsWithTimeout(timeout time.Duration) *GetV1DevicesParams {

	return &GetV1DevicesParams{

		timeout: timeout,
	}
}

// NewGetV1DevicesParamsWithContext creates a new GetV1DevicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1DevicesParamsWithContext(ctx context.Context) *GetV1DevicesParams {

	return &GetV1DevicesParams{

		Context: ctx,
	}
}

// NewGetV1DevicesParamsWithHTTPClient creates a new GetV1DevicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1DevicesParamsWithHTTPClient(client *http.Client) *GetV1DevicesParams {

	return &GetV1DevicesParams{
		HTTPClient: client,
	}
}

/*GetV1DevicesParams contains all the parameters to send to the API endpoint
for the get v1 devices operation typically these are written to a http.Request
*/
type GetV1DevicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 devices params
func (o *GetV1DevicesParams) WithTimeout(timeout time.Duration) *GetV1DevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 devices params
func (o *GetV1DevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 devices params
func (o *GetV1DevicesParams) WithContext(ctx context.Context) *GetV1DevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 devices params
func (o *GetV1DevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 devices params
func (o *GetV1DevicesParams) WithHTTPClient(client *http.Client) *GetV1DevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 devices params
func (o *GetV1DevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
