// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// GetV1DevicesReader is a Reader for the GetV1Devices structure.
type GetV1DevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1DevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1DevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1DevicesOK creates a GetV1DevicesOK with default headers values
func NewGetV1DevicesOK() *GetV1DevicesOK {
	return &GetV1DevicesOK{}
}

/*GetV1DevicesOK handles this case with default header values.

Returns user's devices
*/
type GetV1DevicesOK struct {
	Payload *models.DeviceEntity
}

func (o *GetV1DevicesOK) Error() string {
	return fmt.Sprintf("[GET /v1/devices][%d] getV1DevicesOK  %+v", 200, o.Payload)
}

func (o *GetV1DevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
