// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PostV1DevicesReader is a Reader for the PostV1Devices structure.
type PostV1DevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1DevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostV1DevicesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV1DevicesCreated creates a PostV1DevicesCreated with default headers values
func NewPostV1DevicesCreated() *PostV1DevicesCreated {
	return &PostV1DevicesCreated{}
}

/*PostV1DevicesCreated handles this case with default header values.

Creates new device
*/
type PostV1DevicesCreated struct {
	Payload *models.DeviceEntity
}

func (o *PostV1DevicesCreated) Error() string {
	return fmt.Sprintf("[POST /v1/devices][%d] postV1DevicesCreated  %+v", 201, o.Payload)
}

func (o *PostV1DevicesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
