// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteV1MembershipsIDParams creates a new DeleteV1MembershipsIDParams object
// with the default values initialized.
func NewDeleteV1MembershipsIDParams() *DeleteV1MembershipsIDParams {
	var ()
	return &DeleteV1MembershipsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1MembershipsIDParamsWithTimeout creates a new DeleteV1MembershipsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteV1MembershipsIDParamsWithTimeout(timeout time.Duration) *DeleteV1MembershipsIDParams {
	var ()
	return &DeleteV1MembershipsIDParams{

		timeout: timeout,
	}
}

// NewDeleteV1MembershipsIDParamsWithContext creates a new DeleteV1MembershipsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteV1MembershipsIDParamsWithContext(ctx context.Context) *DeleteV1MembershipsIDParams {
	var ()
	return &DeleteV1MembershipsIDParams{

		Context: ctx,
	}
}

// NewDeleteV1MembershipsIDParamsWithHTTPClient creates a new DeleteV1MembershipsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteV1MembershipsIDParamsWithHTTPClient(client *http.Client) *DeleteV1MembershipsIDParams {
	var ()
	return &DeleteV1MembershipsIDParams{
		HTTPClient: client,
	}
}

/*DeleteV1MembershipsIDParams contains all the parameters to send to the API endpoint
for the delete v1 memberships Id operation typically these are written to a http.Request
*/
type DeleteV1MembershipsIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) WithTimeout(timeout time.Duration) *DeleteV1MembershipsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) WithContext(ctx context.Context) *DeleteV1MembershipsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) WithHTTPClient(client *http.Client) *DeleteV1MembershipsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) WithID(id string) *DeleteV1MembershipsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete v1 memberships Id params
func (o *DeleteV1MembershipsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1MembershipsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
