// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// GetV1MembershipsReader is a Reader for the GetV1Memberships structure.
type GetV1MembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1MembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1MembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1MembershipsOK creates a GetV1MembershipsOK with default headers values
func NewGetV1MembershipsOK() *GetV1MembershipsOK {
	return &GetV1MembershipsOK{}
}

/*GetV1MembershipsOK handles this case with default header values.

Returns user's memberships.
*/
type GetV1MembershipsOK struct {
	Payload *models.MembershipEntity
}

func (o *GetV1MembershipsOK) Error() string {
	return fmt.Sprintf("[GET /v1/memberships][%d] getV1MembershipsOK  %+v", 200, o.Payload)
}

func (o *GetV1MembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MembershipEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
