// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PostV1MembershipsReader is a Reader for the PostV1Memberships structure.
type PostV1MembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1MembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostV1MembershipsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV1MembershipsCreated creates a PostV1MembershipsCreated with default headers values
func NewPostV1MembershipsCreated() *PostV1MembershipsCreated {
	return &PostV1MembershipsCreated{}
}

/*PostV1MembershipsCreated handles this case with default header values.

Creates a new membership.
*/
type PostV1MembershipsCreated struct {
	Payload *models.MembershipEntity
}

func (o *PostV1MembershipsCreated) Error() string {
	return fmt.Sprintf("[POST /v1/memberships][%d] postV1MembershipsCreated  %+v", 201, o.Payload)
}

func (o *PostV1MembershipsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MembershipEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
