// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutV1MembershipsIDJoinParams creates a new PutV1MembershipsIDJoinParams object
// with the default values initialized.
func NewPutV1MembershipsIDJoinParams() *PutV1MembershipsIDJoinParams {
	var ()
	return &PutV1MembershipsIDJoinParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutV1MembershipsIDJoinParamsWithTimeout creates a new PutV1MembershipsIDJoinParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutV1MembershipsIDJoinParamsWithTimeout(timeout time.Duration) *PutV1MembershipsIDJoinParams {
	var ()
	return &PutV1MembershipsIDJoinParams{

		timeout: timeout,
	}
}

// NewPutV1MembershipsIDJoinParamsWithContext creates a new PutV1MembershipsIDJoinParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutV1MembershipsIDJoinParamsWithContext(ctx context.Context) *PutV1MembershipsIDJoinParams {
	var ()
	return &PutV1MembershipsIDJoinParams{

		Context: ctx,
	}
}

// NewPutV1MembershipsIDJoinParamsWithHTTPClient creates a new PutV1MembershipsIDJoinParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutV1MembershipsIDJoinParamsWithHTTPClient(client *http.Client) *PutV1MembershipsIDJoinParams {
	var ()
	return &PutV1MembershipsIDJoinParams{
		HTTPClient: client,
	}
}

/*PutV1MembershipsIDJoinParams contains all the parameters to send to the API endpoint
for the put v1 memberships Id join operation typically these are written to a http.Request
*/
type PutV1MembershipsIDJoinParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) WithTimeout(timeout time.Duration) *PutV1MembershipsIDJoinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) WithContext(ctx context.Context) *PutV1MembershipsIDJoinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) WithHTTPClient(client *http.Client) *PutV1MembershipsIDJoinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) WithID(id string) *PutV1MembershipsIDJoinParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put v1 memberships Id join params
func (o *PutV1MembershipsIDJoinParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutV1MembershipsIDJoinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
