// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PutV1MembershipsIDReader is a Reader for the PutV1MembershipsID structure.
type PutV1MembershipsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1MembershipsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1MembershipsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1MembershipsIDOK creates a PutV1MembershipsIDOK with default headers values
func NewPutV1MembershipsIDOK() *PutV1MembershipsIDOK {
	return &PutV1MembershipsIDOK{}
}

/*PutV1MembershipsIDOK handles this case with default header values.

Updates a membership.
*/
type PutV1MembershipsIDOK struct {
	Payload *models.MembershipEntity
}

func (o *PutV1MembershipsIDOK) Error() string {
	return fmt.Sprintf("[PUT /v1/memberships/{id}][%d] putV1MembershipsIdOK  %+v", 200, o.Payload)
}

func (o *PutV1MembershipsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MembershipEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
