// Code generated by go-swagger; DO NOT EDIT.

package memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// PutV1MembershipsIDJoinReader is a Reader for the PutV1MembershipsIDJoin structure.
type PutV1MembershipsIDJoinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1MembershipsIDJoinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1MembershipsIDJoinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1MembershipsIDJoinOK creates a PutV1MembershipsIDJoinOK with default headers values
func NewPutV1MembershipsIDJoinOK() *PutV1MembershipsIDJoinOK {
	return &PutV1MembershipsIDJoinOK{}
}

/*PutV1MembershipsIDJoinOK handles this case with default header values.

Join to invited room
*/
type PutV1MembershipsIDJoinOK struct {
	Payload *models.MembershipEntity
}

func (o *PutV1MembershipsIDJoinOK) Error() string {
	return fmt.Sprintf("[PUT /v1/memberships/{id}/join][%d] putV1MembershipsIdJoinOK  %+v", 200, o.Payload)
}

func (o *PutV1MembershipsIDJoinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MembershipEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
