// Code generated by go-swagger; DO NOT EDIT.

package access_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteV1AccessTokensAccessTokenIDParams creates a new DeleteV1AccessTokensAccessTokenIDParams object
// with the default values initialized.
func NewDeleteV1AccessTokensAccessTokenIDParams() *DeleteV1AccessTokensAccessTokenIDParams {
	var ()
	return &DeleteV1AccessTokensAccessTokenIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1AccessTokensAccessTokenIDParamsWithTimeout creates a new DeleteV1AccessTokensAccessTokenIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteV1AccessTokensAccessTokenIDParamsWithTimeout(timeout time.Duration) *DeleteV1AccessTokensAccessTokenIDParams {
	var ()
	return &DeleteV1AccessTokensAccessTokenIDParams{

		timeout: timeout,
	}
}

// NewDeleteV1AccessTokensAccessTokenIDParamsWithContext creates a new DeleteV1AccessTokensAccessTokenIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteV1AccessTokensAccessTokenIDParamsWithContext(ctx context.Context) *DeleteV1AccessTokensAccessTokenIDParams {
	var ()
	return &DeleteV1AccessTokensAccessTokenIDParams{

		Context: ctx,
	}
}

// NewDeleteV1AccessTokensAccessTokenIDParamsWithHTTPClient creates a new DeleteV1AccessTokensAccessTokenIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteV1AccessTokensAccessTokenIDParamsWithHTTPClient(client *http.Client) *DeleteV1AccessTokensAccessTokenIDParams {
	var ()
	return &DeleteV1AccessTokensAccessTokenIDParams{
		HTTPClient: client,
	}
}

/*DeleteV1AccessTokensAccessTokenIDParams contains all the parameters to send to the API endpoint
for the delete v1 access tokens access token Id operation typically these are written to a http.Request
*/
type DeleteV1AccessTokensAccessTokenIDParams struct {

	/*AccessTokenID*/
	AccessTokenID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) WithTimeout(timeout time.Duration) *DeleteV1AccessTokensAccessTokenIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) WithContext(ctx context.Context) *DeleteV1AccessTokensAccessTokenIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) WithHTTPClient(client *http.Client) *DeleteV1AccessTokensAccessTokenIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessTokenID adds the accessTokenID to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) WithAccessTokenID(accessTokenID string) *DeleteV1AccessTokensAccessTokenIDParams {
	o.SetAccessTokenID(accessTokenID)
	return o
}

// SetAccessTokenID adds the accessTokenId to the delete v1 access tokens access token Id params
func (o *DeleteV1AccessTokensAccessTokenIDParams) SetAccessTokenID(accessTokenID string) {
	o.AccessTokenID = accessTokenID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1AccessTokensAccessTokenIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param access_token_id
	if err := r.SetPathParam("access_token_id", o.AccessTokenID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
