// Code generated by go-swagger; DO NOT EDIT.

package access_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// DeleteV1AccessTokensAccessTokenIDReader is a Reader for the DeleteV1AccessTokensAccessTokenID structure.
type DeleteV1AccessTokensAccessTokenIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1AccessTokensAccessTokenIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteV1AccessTokensAccessTokenIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteV1AccessTokensAccessTokenIDOK creates a DeleteV1AccessTokensAccessTokenIDOK with default headers values
func NewDeleteV1AccessTokensAccessTokenIDOK() *DeleteV1AccessTokensAccessTokenIDOK {
	return &DeleteV1AccessTokensAccessTokenIDOK{}
}

/*DeleteV1AccessTokensAccessTokenIDOK handles this case with default header values.

Delete a access_token
*/
type DeleteV1AccessTokensAccessTokenIDOK struct {
	Payload *models.AccessTokenEntity
}

func (o *DeleteV1AccessTokensAccessTokenIDOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/access_tokens/{access_token_id}][%d] deleteV1AccessTokensAccessTokenIdOK  %+v", 200, o.Payload)
}

func (o *DeleteV1AccessTokensAccessTokenIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessTokenEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
