// Code generated by go-swagger; DO NOT EDIT.

package access_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// GetV1AccessTokensReader is a Reader for the GetV1AccessTokens structure.
type GetV1AccessTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1AccessTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1AccessTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1AccessTokensOK creates a GetV1AccessTokensOK with default headers values
func NewGetV1AccessTokensOK() *GetV1AccessTokensOK {
	return &GetV1AccessTokensOK{}
}

/*GetV1AccessTokensOK handles this case with default header values.

Returns user's access tokens
*/
type GetV1AccessTokensOK struct {
	Payload *models.AccessTokenEntity
}

func (o *GetV1AccessTokensOK) Error() string {
	return fmt.Sprintf("[GET /v1/access_tokens][%d] getV1AccessTokensOK  %+v", 200, o.Payload)
}

func (o *GetV1AccessTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessTokenEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
