// Code generated by go-swagger; DO NOT EDIT.

package access_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostV1AccessTokensParams creates a new PostV1AccessTokensParams object
// with the default values initialized.
func NewPostV1AccessTokensParams() *PostV1AccessTokensParams {
	var ()
	return &PostV1AccessTokensParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1AccessTokensParamsWithTimeout creates a new PostV1AccessTokensParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostV1AccessTokensParamsWithTimeout(timeout time.Duration) *PostV1AccessTokensParams {
	var ()
	return &PostV1AccessTokensParams{

		timeout: timeout,
	}
}

// NewPostV1AccessTokensParamsWithContext creates a new PostV1AccessTokensParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostV1AccessTokensParamsWithContext(ctx context.Context) *PostV1AccessTokensParams {
	var ()
	return &PostV1AccessTokensParams{

		Context: ctx,
	}
}

// NewPostV1AccessTokensParamsWithHTTPClient creates a new PostV1AccessTokensParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostV1AccessTokensParamsWithHTTPClient(client *http.Client) *PostV1AccessTokensParams {
	var ()
	return &PostV1AccessTokensParams{
		HTTPClient: client,
	}
}

/*PostV1AccessTokensParams contains all the parameters to send to the API endpoint
for the post v1 access tokens operation typically these are written to a http.Request
*/
type PostV1AccessTokensParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post v1 access tokens params
func (o *PostV1AccessTokensParams) WithTimeout(timeout time.Duration) *PostV1AccessTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 access tokens params
func (o *PostV1AccessTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 access tokens params
func (o *PostV1AccessTokensParams) WithContext(ctx context.Context) *PostV1AccessTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 access tokens params
func (o *PostV1AccessTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 access tokens params
func (o *PostV1AccessTokensParams) WithHTTPClient(client *http.Client) *PostV1AccessTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 access tokens params
func (o *PostV1AccessTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the post v1 access tokens params
func (o *PostV1AccessTokensParams) WithName(name string) *PostV1AccessTokensParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post v1 access tokens params
func (o *PostV1AccessTokensParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1AccessTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
