// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/raa0121/go-kokoro-io/models"
)

// DeleteV1MessagesMessageIDReader is a Reader for the DeleteV1MessagesMessageID structure.
type DeleteV1MessagesMessageIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1MessagesMessageIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteV1MessagesMessageIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteV1MessagesMessageIDOK creates a DeleteV1MessagesMessageIDOK with default headers values
func NewDeleteV1MessagesMessageIDOK() *DeleteV1MessagesMessageIDOK {
	return &DeleteV1MessagesMessageIDOK{}
}

/*DeleteV1MessagesMessageIDOK handles this case with default header values.

Delete a message.
*/
type DeleteV1MessagesMessageIDOK struct {
	Payload *models.MessageEntity
}

func (o *DeleteV1MessagesMessageIDOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/messages/{message_id}][%d] deleteV1MessagesMessageIdOK  %+v", 200, o.Payload)
}

func (o *DeleteV1MessagesMessageIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
