// Code generated by go-swagger; DO NOT EDIT.

package bot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostV1BotChannelsChannelIDMessagesParams creates a new PostV1BotChannelsChannelIDMessagesParams object
// with the default values initialized.
func NewPostV1BotChannelsChannelIDMessagesParams() *PostV1BotChannelsChannelIDMessagesParams {
	var ()
	return &PostV1BotChannelsChannelIDMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1BotChannelsChannelIDMessagesParamsWithTimeout creates a new PostV1BotChannelsChannelIDMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostV1BotChannelsChannelIDMessagesParamsWithTimeout(timeout time.Duration) *PostV1BotChannelsChannelIDMessagesParams {
	var ()
	return &PostV1BotChannelsChannelIDMessagesParams{

		timeout: timeout,
	}
}

// NewPostV1BotChannelsChannelIDMessagesParamsWithContext creates a new PostV1BotChannelsChannelIDMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostV1BotChannelsChannelIDMessagesParamsWithContext(ctx context.Context) *PostV1BotChannelsChannelIDMessagesParams {
	var ()
	return &PostV1BotChannelsChannelIDMessagesParams{

		Context: ctx,
	}
}

// NewPostV1BotChannelsChannelIDMessagesParamsWithHTTPClient creates a new PostV1BotChannelsChannelIDMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostV1BotChannelsChannelIDMessagesParamsWithHTTPClient(client *http.Client) *PostV1BotChannelsChannelIDMessagesParams {
	var ()
	return &PostV1BotChannelsChannelIDMessagesParams{
		HTTPClient: client,
	}
}

/*PostV1BotChannelsChannelIDMessagesParams contains all the parameters to send to the API endpoint
for the post v1 bot channels channel Id messages operation typically these are written to a http.Request
*/
type PostV1BotChannelsChannelIDMessagesParams struct {

	/*ChannelID*/
	ChannelID string
	/*DisplayName*/
	DisplayName *string
	/*ExpandEmbedContents*/
	ExpandEmbedContents *bool
	/*Message*/
	Message string
	/*Nsfw*/
	Nsfw *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithTimeout(timeout time.Duration) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithContext(ctx context.Context) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithHTTPClient(client *http.Client) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithChannelID(channelID string) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithDisplayName adds the displayName to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithDisplayName(displayName *string) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetDisplayName(displayName)
	return o
}

// SetDisplayName adds the displayName to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
}

// WithExpandEmbedContents adds the expandEmbedContents to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithExpandEmbedContents(expandEmbedContents *bool) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetExpandEmbedContents(expandEmbedContents)
	return o
}

// SetExpandEmbedContents adds the expandEmbedContents to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetExpandEmbedContents(expandEmbedContents *bool) {
	o.ExpandEmbedContents = expandEmbedContents
}

// WithMessage adds the message to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithMessage(message string) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetMessage(message string) {
	o.Message = message
}

// WithNsfw adds the nsfw to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) WithNsfw(nsfw *bool) *PostV1BotChannelsChannelIDMessagesParams {
	o.SetNsfw(nsfw)
	return o
}

// SetNsfw adds the nsfw to the post v1 bot channels channel Id messages params
func (o *PostV1BotChannelsChannelIDMessagesParams) SetNsfw(nsfw *bool) {
	o.Nsfw = nsfw
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1BotChannelsChannelIDMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", o.ChannelID); err != nil {
		return err
	}

	if o.DisplayName != nil {

		// form param display_name
		var frDisplayName string
		if o.DisplayName != nil {
			frDisplayName = *o.DisplayName
		}
		fDisplayName := frDisplayName
		if fDisplayName != "" {
			if err := r.SetFormParam("display_name", fDisplayName); err != nil {
				return err
			}
		}

	}

	if o.ExpandEmbedContents != nil {

		// form param expand_embed_contents
		var frExpandEmbedContents bool
		if o.ExpandEmbedContents != nil {
			frExpandEmbedContents = *o.ExpandEmbedContents
		}
		fExpandEmbedContents := swag.FormatBool(frExpandEmbedContents)
		if fExpandEmbedContents != "" {
			if err := r.SetFormParam("expand_embed_contents", fExpandEmbedContents); err != nil {
				return err
			}
		}

	}

	// form param message
	frMessage := o.Message
	fMessage := frMessage
	if fMessage != "" {
		if err := r.SetFormParam("message", fMessage); err != nil {
			return err
		}
	}

	if o.Nsfw != nil {

		// form param nsfw
		var frNsfw bool
		if o.Nsfw != nil {
			frNsfw = *o.Nsfw
		}
		fNsfw := swag.FormatBool(frNsfw)
		if fNsfw != "" {
			if err := r.SetFormParam("nsfw", fNsfw); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
