// Code generated by go-swagger; DO NOT EDIT.

package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1ProfilesParams creates a new GetV1ProfilesParams object
// with the default values initialized.
func NewGetV1ProfilesParams() *GetV1ProfilesParams {

	return &GetV1ProfilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ProfilesParamsWithTimeout creates a new GetV1ProfilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1ProfilesParamsWithTimeout(timeout time.Duration) *GetV1ProfilesParams {

	return &GetV1ProfilesParams{

		timeout: timeout,
	}
}

// NewGetV1ProfilesParamsWithContext creates a new GetV1ProfilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1ProfilesParamsWithContext(ctx context.Context) *GetV1ProfilesParams {

	return &GetV1ProfilesParams{

		Context: ctx,
	}
}

// NewGetV1ProfilesParamsWithHTTPClient creates a new GetV1ProfilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1ProfilesParamsWithHTTPClient(client *http.Client) *GetV1ProfilesParams {

	return &GetV1ProfilesParams{
		HTTPClient: client,
	}
}

/*GetV1ProfilesParams contains all the parameters to send to the API endpoint
for the get v1 profiles operation typically these are written to a http.Request
*/
type GetV1ProfilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 profiles params
func (o *GetV1ProfilesParams) WithTimeout(timeout time.Duration) *GetV1ProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 profiles params
func (o *GetV1ProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 profiles params
func (o *GetV1ProfilesParams) WithContext(ctx context.Context) *GetV1ProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 profiles params
func (o *GetV1ProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 profiles params
func (o *GetV1ProfilesParams) WithHTTPClient(client *http.Client) *GetV1ProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 profiles params
func (o *GetV1ProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
