// Code generated by go-swagger; DO NOT EDIT.

package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1ProfilesMeParams creates a new GetV1ProfilesMeParams object
// with the default values initialized.
func NewGetV1ProfilesMeParams() *GetV1ProfilesMeParams {

	return &GetV1ProfilesMeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ProfilesMeParamsWithTimeout creates a new GetV1ProfilesMeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1ProfilesMeParamsWithTimeout(timeout time.Duration) *GetV1ProfilesMeParams {

	return &GetV1ProfilesMeParams{

		timeout: timeout,
	}
}

// NewGetV1ProfilesMeParamsWithContext creates a new GetV1ProfilesMeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1ProfilesMeParamsWithContext(ctx context.Context) *GetV1ProfilesMeParams {

	return &GetV1ProfilesMeParams{

		Context: ctx,
	}
}

// NewGetV1ProfilesMeParamsWithHTTPClient creates a new GetV1ProfilesMeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1ProfilesMeParamsWithHTTPClient(client *http.Client) *GetV1ProfilesMeParams {

	return &GetV1ProfilesMeParams{
		HTTPClient: client,
	}
}

/*GetV1ProfilesMeParams contains all the parameters to send to the API endpoint
for the get v1 profiles me operation typically these are written to a http.Request
*/
type GetV1ProfilesMeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) WithTimeout(timeout time.Duration) *GetV1ProfilesMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) WithContext(ctx context.Context) *GetV1ProfilesMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) WithHTTPClient(client *http.Client) *GetV1ProfilesMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 profiles me params
func (o *GetV1ProfilesMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ProfilesMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
