// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AvatarEntity avatar entity
// swagger:model AvatarEntity
type AvatarEntity struct {

	// デフォルトアバターであるか
	IsDefault bool `json:"is_default,omitempty"`

	// 正方形画像の縦横サイズ（単位：px）
	Size int32 `json:"size,omitempty"`

	// 画像のURL
	URL string `json:"url,omitempty"`
}

// Validate validates this avatar entity
func (m *AvatarEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AvatarEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AvatarEntity) UnmarshalBinary(b []byte) error {
	var res AvatarEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
