// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProfileEntity Returns all user's profile except yours
// swagger:model ProfileEntity
type ProfileEntity struct {

	// アーカイブ済か
	Archived bool `json:"archived,omitempty"`

	// アバターURL
	Avatar string `json:"avatar,omitempty"`

	// avatars
	Avatars []*AvatarEntity `json:"avatars"`

	// ディスプレイネーム
	DisplayName string `json:"display_name,omitempty"`

	// プロフィールID
	ID string `json:"id,omitempty"`

	// 招待されているチャンネルの数
	InvitedChannelsCount int32 `json:"invited_channels_count,omitempty"`

	// スクリーンネーム
	ScreenName string `json:"screen_name,omitempty"`

	// 種類（user|bot）
	Type string `json:"type,omitempty"`
}

// Validate validates this profile entity
func (m *ProfileEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvatars(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfileEntity) validateAvatars(formats strfmt.Registry) error {

	if swag.IsZero(m.Avatars) { // not required
		return nil
	}

	for i := 0; i < len(m.Avatars); i++ {
		if swag.IsZero(m.Avatars[i]) { // not required
			continue
		}

		if m.Avatars[i] != nil {
			if err := m.Avatars[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("avatars" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProfileEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfileEntity) UnmarshalBinary(b []byte) error {
	var res ProfileEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
